### ISSUE TITLE
Trades are not getting imported

### ISSUE THREAD

**Issue by electricar** [GeneBO98/tradetally#88]
I imported this one trade and added a stop loss value to it.

[trades_export(1).csv](https://github.com/user-attachments/files/23308044/trades_export.1.csv)

Now in the evening I wanted to import these 3 trades/executions (grouping time frame is 5 min in my tradetally import settings), but none of them is getting imported.

[trades_export(2).csv](https://github.com/user-attachments/files/23308051/trades_export.2.csv)

**Comment by GeneBO98** [comment]
I tested and it imported fine. Is it possible that these were imported before? If they are detected in the DB as duplicates then it won't import them. I have also seen a bug before where my trades are not showing in the frontend but are in the DB. This should have been resolved but just so you know.

**Comment by electricar** [comment]
Only the first trade from trades_export(1).csv was in the second file as well.
I have deleted all trades prior to the import in the "Import History" field and still cannot import both files.

**Comment by GeneBO98** [comment]
You might have to delete them from the DB. 
```sql
psql -U trader -d tradetally -c "DELETE FROM trades WHERE symbol = 'MESZ5' RETURNING id, symbol, entry_time
```

**Comment by electricar** [comment]
The trades were never imported before, so not sure why this happens.
I am not sure if I am doing it correctly. I am opening the console for the db container in Portainer and sending your command, but nothing happens. I also tried different users, but again I am not sure what to do.
In my .env the DB_USER is trader and the DB_NAME is tradetally.
In my trades (on the website) I can only see trade from trades_export(1).csv.
The others are not visible as they could never been imported in the first place.

<img width="416" height="401" alt="Image" src="https://github.com/user-attachments/assets/ea9489d2-eebb-42f5-86d6-7dd84ffca361" />

<img width="962" height="343" alt="Image" src="https://github.com/user-attachments/assets/96b4854c-5fed-4d87-b44e-aca552afaf89" />

**Comment by GeneBO98** [comment]
Since you are running in Portainer, are you also running adminer? If so, then you can connect to adminer to look for those trades in the DB. Can you try pulling the latest image and retry the import as well?

**Comment by electricar** [comment]
I don't have adminer currently.
After the latest deployment I could  import the trades, but the very first trade from trades_export(1).csv was imported a second time.

<img width="1731" height="424" alt="Image" src="https://github.com/user-attachments/assets/0c0b2207-6ea3-4198-8f0c-43e9b353b24d" />

**Comment by GeneBO98** [comment]
I am not sure what would be causing that. It doesn't duplicate for me when I test. The import works okay in my test environment. The only thing I could recommend is to install adminer and try to remove any trades that don't appear correctly. I apologize for the problems. I have had to change the DB structure so many times for new features and updates and it hasn't gone super smoothly. Additionally, the duplicate checking function is actually a pretty difficult thing to do since most trade imports don't include a unique ID for the executions.

**Comment by electricar** [comment]
Oh wait, I was not aware that adminer is in the docker compose already.
I opened it, deleted all trades (only the 4 from above were shown) and imported the two files one by one and it worked! Only 3 trades are shown.
But then I deleted all trades in adminer, imported the first file, added a stop loss value to it and imported the second file (remember the trade from the first trade is in the second file as well) and now it imported the first trade again.
It seems that the change (added stop loss value) has to do something with it.

**Comment by GeneBO98** [comment]
Oh good! I am glad that you were able to use Adminer. The information about the stop loss is incredibly helpful! I will look into that.

**Comment by GeneBO98** [comment]
Latest commit should resolve this! :)

**Comment by electricar** [comment]
perfect, thank you :)
